[server]
port = 5000
address = "0.0.0.0"
headless = true
maxUploadSize = 2048

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 5000

[client]
toolbarMode = "minimal"
showErrorDetails = true